-- wx-core-keyboard.ads
-- 
-- Copyright © 2005 Luke A. Guest
--
-- Distributed under the wxWidgets Licence
package wx.Core.Keyboard is
--  pragma Pure(wx.Core.Keyboard);

  type Key_Code_Type is (
    Key_Back,
    Key_Tab,
    Key_Return,
    Key_Escape,
    Key_Space,
    Key_Delete,

    -- Hardware-specific buttons
    Key_Special_1,
    Key_Special_2,
    Key_Special_3,
    Key_Special_4,
    Key_Special_5,
    Key_Special_6,
    Key_Special_7,
    Key_Special_8,
    Key_Special_9,
    Key_Special_10,
    Key_Special_11,
    Key_Special_12,
    Key_Special_13,
    Key_Special_14,
    Key_Special_15,
    Key_Special_16,
    Key_Special_17,
    Key_Special_18,
    Key_Special_19,
    Key_Special_20,

    -- These are, by design, not compatible with unicode characters.
    -- If you want to get a unicode character from a key event, use
    -- wxKeyEvent::GetUnicodeKey instead.
    Key_Start,
    Key_Left_Button,
    Key_Right_Button,
    Key_Cancel,
    Key_Middle_Button,
    Key_Clear,
    Key_Shift,
    Key_Alt,
    Key_Control,
    Key_Menu,
    Key_Pause,
    Key_Capital,
    Key_Prior,  -- Page up
    Key_Next,   -- Page down
    Key_End,
    Key_Home,
    Key_Left,
    Key_Up,
    Key_Right,
    Key_Down,
    Key_Select,
    Key_Print,
    Key_Execute,
    Key_Snapshot,
    Key_Insert,
    Key_Help,
    Key_Numeric_Pad_0,
    Key_Numeric_Pad_1,
    Key_Numeric_Pad_2,
    Key_Numeric_Pad_3,
    Key_Numeric_Pad_4,
    Key_Numeric_Pad_5,
    Key_Numeric_Pad_6,
    Key_Numeric_Pad_7,
    Key_Numeric_Pad_8,
    Key_Numeric_Pad_9,
    Key_Multiply,
    Key_Add,
    Key_Separator,
    Key_Subtract,
    Key_Decimal,
    Key_Divide,
    Key_F1,
    Key_F2,
    Key_F3,
    Key_F4,
    Key_F5,
    Key_F6,
    Key_F7,
    Key_F8,
    Key_F9,
    Key_F10,
    Key_F11,
    Key_F12,
    Key_F13,
    Key_F14,
    Key_F15,
    Key_F16,
    Key_F17,
    Key_F18,
    Key_F19,
    Key_F20,
    Key_F21,
    Key_F22,
    Key_F23,
    Key_F24,
    Key_Number_Lock,
    Key_Scroll,
    Key_Page_Up,
    Key_Page_Down,

    Key_Numeric_Pad_Space,
    Key_Numeric_Pad_Tab,
    Key_Numeric_Pad_Enter,
    Key_Numeric_Pad_F1,
    Key_Numeric_Pad_F2,
    Key_Numeric_Pad_F3,
    Key_Numeric_Pad_F4,
    Key_Numeric_Pad_Home,
    Key_Numeric_Pad_Left,
    Key_Numeric_Pad_Up,
    Key_Numeric_Pad_Right,
    Key_Numeric_Pad_Down,
    Key_Numeric_Pad_Prior,
    Key_Numeric_Pad_Page_Up,
    Key_Numeric_Pad_Next,
    Key_Numeric_Pad_Page_Down,
    Key_Numeric_Pad_End,
    Key_Numeric_Pad_Begin,
    Key_Numeric_Pad_Insert,
    Key_Numeric_Pad_Delete,
    Key_Numeric_Pad_Equal,
    Key_Numeric_Pad_Multiply,
    Key_Numeric_Pad_Add,
    Key_Numeric_Pad_Separator,
    Key_Numeric_Pad_Ssubtract,
    Key_Numeric_Pad_Decimal,
    Key_Numeric_Pad_Divide,

    Key_Windows_Left,
    Key_Windows_Right,
    Key_Windows_Menu,
    Key_Command);

private

  for Key_Code_Type use (
    Key_Back   => 8,
    Key_Tab    => 9,
    Key_Return => 13,
    Key_Escape => 27,
    Key_Space  => 32,
    Key_Delete => 127,

    -- Hardware-specific buttons
    Key_Special_1  => 193,
    Key_Special_2  => 194,
    Key_Special_3  => 195,
    Key_Special_4  => 196,
    Key_Special_5  => 197,
    Key_Special_6  => 198,
    Key_Special_7  => 199,
    Key_Special_8  => 200,
    Key_Special_9  => 201,
    Key_Special_10 => 202,
    Key_Special_11 => 203,
    Key_Special_12 => 204,
    Key_Special_13 => 205,
    Key_Special_14 => 206,
    Key_Special_15 => 207,
    Key_Special_16 => 208,
    Key_Special_17 => 209,
    Key_Special_18 => 210,
    Key_Special_19 => 211,
    Key_Special_20 => 212,
    
    -- These are, by design, not compatible with unicode characters.
    -- If you want to get a unicode character from a key event, use
    -- wxKeyEvent::GetUnicodeKey instead.
    Key_Start          => 300,
    Key_Left_Button    => 301,
    Key_Right_Button   => 302,
    Key_Cancel         => 303,
    Key_Middle_Button  => 304,
    Key_Clear          => 305,
    Key_Shift          => 306,
    Key_Alt            => 307,
    Key_Control        => 308,
    Key_Menu           => 309,
    Key_Pause          => 310,
    Key_Capital        => 311,
    Key_Prior          => 312,  -- Page up
    Key_Next           => 313,   -- Page down
    Key_End            => 314,
    Key_Home           => 315,
    Key_Left           => 316,
    Key_Up             => 317,
    Key_Right          => 318,
    Key_Down           => 319,
    Key_Select         => 320,
    Key_Print          => 321,
    Key_Execute        => 322,
    Key_Snapshot       => 323,
    Key_Insert         => 324,
    Key_Help           => 325,
    Key_Numeric_Pad_0  => 326,
    Key_Numeric_Pad_1  => 327,
    Key_Numeric_Pad_2  => 328,
    Key_Numeric_Pad_3  => 329,
    Key_Numeric_Pad_4  => 330,
    Key_Numeric_Pad_5  => 331,
    Key_Numeric_Pad_6  => 332,
    Key_Numeric_Pad_7  => 333,
    Key_Numeric_Pad_8  => 334,
    Key_Numeric_Pad_9  => 335,
    Key_Multiply       => 336,
    Key_Add            => 337,
    Key_Separator      => 338,
    Key_Subtract       => 339,
    Key_Decimal        => 340,
    Key_Divide         => 341,
    Key_F1             => 342,
    Key_F2             => 343,
    Key_F3             => 344,
    Key_F4             => 345,
    Key_F5             => 346,
    Key_F6             => 347,
    Key_F7             => 348,
    Key_F8             => 349,
    Key_F9             => 350,
    Key_F10            => 351,
    Key_F11            => 352,
    Key_F12            => 353,
    Key_F13            => 354,
    Key_F14            => 355,
    Key_F15            => 356,
    Key_F16            => 357,
    Key_F17            => 358,
    Key_F18            => 359,
    Key_F19            => 360,
    Key_F20            => 361,
    Key_F21            => 362,
    Key_F22            => 363,
    Key_F23            => 364,
    Key_F24            => 365,
    Key_Number_Lock    => 366,
    Key_Scroll         => 367,
    Key_Page_Up        => 368,
    Key_Page_Down      => 369,

    Key_Numeric_Pad_Space     => 370,
    Key_Numeric_Pad_Tab       => 371,
    Key_Numeric_Pad_Enter     => 372,
    Key_Numeric_Pad_F1        => 373,
    Key_Numeric_Pad_F2        => 374,
    Key_Numeric_Pad_F3        => 375,
    Key_Numeric_Pad_F4        => 376,
    Key_Numeric_Pad_Home      => 377,
    Key_Numeric_Pad_Left      => 378,
    Key_Numeric_Pad_Up        => 379,
    Key_Numeric_Pad_Right     => 380,
    Key_Numeric_Pad_Down      => 381,
    Key_Numeric_Pad_Prior     => 382,
    Key_Numeric_Pad_Page_Up   => 383,
    Key_Numeric_Pad_Next      => 384,
    Key_Numeric_Pad_Page_Down => 385,
    Key_Numeric_Pad_End       => 386,
    Key_Numeric_Pad_Begin     => 387,
    Key_Numeric_Pad_Insert    => 388,
    Key_Numeric_Pad_Delete    => 389,
    Key_Numeric_Pad_Equal     => 390,
    Key_Numeric_Pad_Multiply  => 391,
    Key_Numeric_Pad_Add       => 392,
    Key_Numeric_Pad_Separator => 393,
    Key_Numeric_Pad_Ssubtract => 394,
    Key_Numeric_Pad_Decimal   => 395,
    Key_Numeric_Pad_Divide    => 396,

    Key_Windows_Left  => 397,
    Key_Windows_Right => 398,
    Key_Windows_Menu  => 399,
    Key_Command       => 400);
    
end wx.Core.Keyboard;
